title: CDPI - IFB / Campus Brasília
description: Site da Coordenação de Pesquisa e Inovação do Campus Brasília do IFB

url: http://cdpibrasilia.github.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Sobre
   url: /about
 - title: Contato
   url: /contact

social:
   github: 
   twitter: 
   facebook: 
   email: cdpi.ifbbrasilia@gmail.com

google_analytics: "UA-58263416-1"
